export default [
  'apothecary',
  'architect',
  'armorer',
  'artisan',
  'baker',
  'barkeep',
  'bee keeper',
  'beetle hunter',
  'bird drover',
  'brewer',
  'butcher',
  'cloth dyer',
  'cobbler',
  'cook',
  'crackpot',
  'doctor',
  'dontler farmer',
  'dyer',
  'farmer',
  'fisher',
  'fortune-teller',
  'fruit monger',
  'furrier',
  'gatherer',
  'glass blower',
  'goose herder',
  'guard',
  'herder',
  'holy-folk',
  'hunter',
  'itinerant',
  'jeweler',
  'laborer',
  'lost soul',
  'magistrate',
  'merchant',
  'miller',
  'monger',
  'musician',
  'navigator',
  'net maker',
  'noble',
  'orphan',
  'peasant',
  'peddler',
  'pirate',
  'priest',
  'potter',
  'rancher',
  'ray fisher',
  'root gatherer',
  'ropemaker',
  'roustabout',
  'sailor',
  'scavenger',
  'scribe',
  'scrivener',
  'servant',
  'ship builder',
  'shop minder',
  'silk maker',
  'smith',
  'stevedore',
  'steward',
  'stoneworker',
  'tailor',
  'trapper',
  'treasure hunter',
  'vagabond',
  'winch carter',
  'wood shaper',
  'woodworker',
];
