export default [
  { name: 'Plain Clothes', cost: 5, kind: 'clothes', traits: [] },
  {
    name: 'Artisans Clothes',
    cost: 10,
    kind: 'clothes',
    traits: ['Pockets for one extra item'],
  },
  {
    name: 'Leather Armor',
    cost: 20,
    kind: 'armor',
    traits: ['Two Defense', 'Light'],
  },
  {
    name: 'Chainmail Armor',
    cost: 40,
    kind: 'armor',
    traits: ['Four Defese', 'Medium'],
  },
  {
    name: 'Banded Armor',
    cost: 50,
    kind: 'armor',
    traits: ['Five Defense', 'Heavy'],
  },
  {
    name: 'Carapace Armor',
    cost: 100,
    kind: 'armor',
    traits: ['Six Defense', 'Heavy'],
  },
  {
    name: 'Shield',
    cost: 20,
    kind: 'shield',
    traits: ['Two Armour', 'Subtract Two from Attacks'],
  },
  {
    name: 'Staff',
    cost: 5,
    kind: 'weapon',
    traits: ['Four-sided Damage Dice'],
  },
  {
    name: 'Sling',
    cost: 5,
    kind: 'weapon',
    traits: ['Four-sided Damage Dice', 'Ranged', 'Uses Stones'],
  },
  {
    name: 'Dagger',
    cost: 10,
    kind: 'weapon',
    traits: ['Four-sided Damage Dice', 'Throwable', 'Small'],
  },
  { name: 'Club', cost: 10, kind: 'weapon', traits: ['Six-sided Damage Dice'] },
  {
    name: 'Hatchet',
    cost: 10,
    kind: 'weapon',
    traits: ['Six-sided Damage Dice', 'Throwable'],
  },
  {
    name: 'Spear',
    cost: 20,
    kind: 'weapon',
    traits: ['Six-sided Damage Dice', 'Long', 'Throwable'],
  },
  {
    name: 'Sword',
    cost: 25,
    kind: 'weapon',
    traits: ['Eight-sided Damage Dice'],
  },
  {
    name: 'Axe',
    cost: 25,
    kind: 'weapon',
    traits: ['Eight-sided Damage Dice'],
  },
  {
    name: 'Big Sword',
    cost: 50,
    kind: 'weapon',
    traits: ['Ten-sided Damage Dice', 'Two-handed', 'Large'],
  },
  {
    name: 'Big Axe',
    cost: 50,
    kind: 'weapon',
    traits: ['Ten-sided Damage Dice', 'Two-handed', 'Large'],
  },
  {
    name: 'Bow',
    cost: 25,
    kind: 'weapon',
    traits: ['Six-sided Damage Dice', 'Two-handed', 'Ranged', 'Uses Arrows'],
  },
  {
    name: 'Big Bow',
    cost: 75,
    kind: 'weapon',
    traits: [
      'Eight-sided Damage Dice',
      'Two-handed',
      'Large',
      'Ranged',
      'Uses Arrows',
    ],
  },
  {
    name: 'Twenty Five Arrows',
    cost: 5,
    kind: 'ammunition',
    traits: ['For Bows and Big Bows'],
  },
  { name: 'Ten Stones', cost: 0, kind: 'ammunition', traits: ['For Slings'] },
  {
    name: 'Backpack',
    cost: 25,
    kind: 'equipment',
    traits: ['Carry Three More Items'],
  },
  {
    name: 'Pouch',
    cost: 10,
    kind: 'equipment',
    traits: ['Carry Two More Items'],
  },
  { name: 'Rope', cost: 5, kind: 'equipment', traits: ['Fifty foot length'] },
  {
    name: 'Book',
    cost: 25,
    kind: 'equipment',
    traits: ['Empty or filled with words'],
  },
  {
    name: 'Small Tent',
    cost: 25,
    kind: 'equipment',
    traits: ['Sleeps one, two uncomfortably'],
  },
  {
    name: 'Large Tent',
    cost: 100,
    kind: 'equipment',
    traits: ['Sleeps five, eight uncomfortably'],
  },
  {
    name: 'Wooden Pole',
    cost: 5,
    kind: 'equipment',
    traits: ['Ten feet long'],
  },
  {
    name: 'Six torches',
    cost: 10,
    kind: 'equipment',
    traits: ['Each one burns for one hour'],
  },
];
