export default [
  // Clothing
  {
    name: 'Artisans Clothes',
    cost: 10,
    kind: 'clothes',
    traits: ['Pockets for one extra item'],
  },
  {
    name: 'Carapace Armor',
    cost: 100,
    kind: 'armor',
    traits: ['Six Defense', 'Heavy'],
  },
  {
    name: 'Chain Mail Armor',
    cost: 40,
    kind: 'armor',
    traits: ['Four Defese', 'Medium'],
  },
  {
    name: 'Fish Leather Armor',
    cost: 20,
    kind: 'armor',
    traits: ['Two Defense', 'Light'],
  },
  {
    name: 'Iron Banded Armor',
    cost: 50,
    kind: 'armor',
    traits: ['Five Defense', 'Heavy'],
  },
  { name: 'Plain Clothes', cost: 5, kind: 'clothes', traits: [] },
  // Weapons
  {
    name: 'Axe',
    cost: 25,
    kind: 'weapon',
    traits: ['Eight-sided Damage Dice'],
  },
  {
    name: 'Bow',
    cost: 25,
    kind: 'weapon',
    traits: ['Six-sided Damage Dice', 'Two-handed', 'Ranged', 'Uses Arrows'],
  },
  { name: 'Club', cost: 10, kind: 'weapon', traits: ['Six-sided Damage Dice'] },
  {
    name: 'Dagger',
    cost: 10,
    kind: 'weapon',
    traits: ['Four-sided Damage Dice', 'Throwable', 'Small'],
  },
  {
    name: 'Hatchet',
    cost: 10,
    kind: 'weapon',
    traits: ['Six-sided Damage Dice', 'Throwable'],
  },
  {
    name: 'Large Axe',
    cost: 50,
    kind: 'weapon',
    traits: ['Ten-sided Damage Dice', 'Two-handed', 'Large'],
  },
  {
    name: 'Large Bow',
    cost: 75,
    kind: 'weapon',
    traits: [
      'Eight-sided Damage Dice',
      'Two-handed',
      'Large',
      'Ranged',
      'Uses Arrows',
    ],
  },
  {
    name: 'Large Sword',
    cost: 50,
    kind: 'weapon',
    traits: ['Ten-sided Damage Dice', 'Two-handed', 'Large'],
  },
  {
    name: 'Sling',
    cost: 5,
    kind: 'weapon',
    traits: ['Four-sided Damage Dice', 'Ranged', 'Uses Stones'],
  },
  {
    name: 'Spear',
    cost: 20,
    kind: 'weapon',
    traits: ['Six-sided Damage Dice', 'Long', 'Throwable', 'Two-handed'],
  },
  {
    name: 'Staff',
    cost: 5,
    kind: 'weapon',
    traits: ['Four-sided Damage Dice', 'Two-handed'],
  },
  {
    name: 'Sword',
    cost: 25,
    kind: 'weapon',
    traits: ['Eight-sided Damage Dice', 'Small', 'Throwable'],
  },
  // Ammunition
  {
    name: 'Twenty Five Arrows',
    cost: 5,
    kind: 'ammunition',
    traits: ['For Bows and Big Bows'],
  },
  { name: 'Ten Stones', cost: 0, kind: 'ammunition', traits: ['For Slings'] },
  // Equipment
  {
    name: 'Backpack',
    cost: 25,
    kind: 'equipment',
    traits: ['Carry Three More Items'],
  },
  {
    name: 'Book',
    cost: 25,
    kind: 'equipment',
    traits: ['Empty or filled with words'],
  },
  {
    name: 'Bucket',
    cost: 10,
    kind: 'equipment',
    traits: ['Large or Small'],
  },
  {
    name: 'Flint Stone',
    cost: 10,
    kind: 'equipment',
    traits: ['For starting Fires'],
  },
  {
    name: 'Jar of Wax',
    cost: 5,
    kind: 'equipment',
    traits: ['To refill a lantern or use as sealant'],
  },
  {
    name: 'Jug',
    cost: 10,
    kind: 'equipment',
    traits: ['Large or Small'],
  },
  {
    name: 'Lantern',
    cost: 25,
    kind: 'equipment',
    traits: ['Burns for six hours before it must be refilled with wax'],
  },
  {
    name: 'Large Cart',
    cost: 200,
    kind: 'equipment',
    traits: ['Pulled by three folk', 'carries eight folk or fifty items'],
  },
  {
    name: 'Large Tent',
    cost: 50,
    kind: 'equipment',
    traits: ['Sleeps five, eight uncomfortably'],
  },
  {
    name: 'Net',
    cost: 10,
    kind: 'equipment',
    traits: ['For catching fish—or perhaps folk'],
  },
  {
    name: 'Oar',
    cost: 10,
    kind: 'equipment',
    traits: ['For rowing'],
  },
  {
    name: 'Paddle',
    cost: 10,
    kind: 'equipment',
    traits: ['For paddling'],
  },
  {
    name: 'Pouch',
    cost: 10,
    kind: 'equipment',
    traits: ['Carry two Items as one'],
  },
  { name: 'Rope', cost: 5, kind: 'equipment', traits: ['Fifty foot length'] },
  {
    name: 'Sailboat',
    cost: 1500,
    kind: 'equipment',
    traits: ['Carries ten folk and one hundred items across the sea'],
  },
  {
    name: 'Saw',
    cost: 10,
    kind: 'equipment',
    traits: ['For sawing'],
  },
  {
    name: 'Shield',
    cost: 20,
    kind: 'equipment',
    traits: ['Two Armour', 'Subtract Two from Attacks'],
  },
  {
    name: 'Shovel',
    cost: 10,
    kind: 'equipment',
    traits: ['For digging'],
  },
  {
    name: 'Small Cart',
    cost: 50,
    kind: 'equipment',
    traits: ['Pulled by one folk', 'carries two folk or twelve Items'],
  },
  {
    name: 'Small Rowboat',
    cost: 100,
    kind: 'equipment',
    traits: ['Carries four folk or twenty five Items'],
  },
  {
    name: 'Small Sailboat',
    cost: 250,
    kind: 'equipment',
    traits: ['Carries four folk or twenty five Items'],
  },
  {
    name: 'Small Tent',
    cost: 25,
    kind: 'equipment',
    traits: ['Sleeps one, two uncomfortably'],
  },
  {
    name: 'Spade',
    cost: 10,
    kind: 'equipment',
    traits: ['For digging'],
  },
  {
    name: 'Tool Kit',
    cost: 0,
    kind: 'equipment',
    traits: ['Hand tools for a specific craft or trade'],
  },
  {
    name: 'Torches',
    cost: 10,
    kind: 'equipment',
    traits: ['Six', 'Each one burns for one hour'],
  },
  {
    name: 'Wooden Pole',
    cost: 5,
    kind: 'equipment',
    traits: ['Ten feet long'],
  },
];
