export default {
  first: [
    { name: 'Abigael', gender: 'f' },
    { name: 'Afari' },
    { name: 'Agnes', gender: 'f' },
    { name: 'Antía', gender: 'f' },
    { name: 'Antony', gender: 'm' },
    { name: 'Basila', gender: 'f' },
    { name: 'Brais' },
    { name: 'Bryn' },
    { name: 'Burnet' },
    { name: 'Cora', gender: 'f' },
    { name: 'Deka' },
    { name: 'Delfina', gender: 'f' },
    { name: 'Desta', gender: 'f' },
    { name: 'Farn', gender: 'm' },
    { name: 'Farina', gender: 'f' },
    { name: 'Farruco', gender: 'm' },
    { name: 'Froderic', gender: 'm' },
    { name: 'Foot', gender: 'm' },
    { name: 'Gerrit', gender: 'm' },
    { name: 'Glen', gender: 'm' },
    { name: 'Helewis', gender: 'f' },
    { name: 'Iria', gender: 'f' },
    { name: 'Joeri' },
    { name: 'Lazo' },
    { name: 'Lili', gender: 'f' },
    { name: 'Lisanne', gender: 'f' },
    { name: 'Loek', gender: 'm' },
    { name: 'Loes', gender: 'f' },
    { name: 'Lua', gender: 'f' },
    { name: 'Manue' },
    { name: 'Mari' },
    { name: 'Marta', gender: 'f' },
    { name: 'Martin', gender: 'm' },
    { name: 'Matild', gender: 'f' },
    { name: 'Mirana', gender: 'f' },
    { name: 'Moreno', gender: 'm' },
    { name: 'Myril', gender: 'f' },
    { name: 'Nelke' },
    { name: 'Nia', gender: 'f' },
    { name: 'Nuru' },
    { name: 'Onja', gender: 'f' },
    { name: 'Petra', gender: 'f' },
    { name: 'Qoz', gender: 'm' },
    { name: 'Raissa', gender: 'f' },
    { name: 'Rens' },
    { name: 'Rut', gender: 'm' },
    { name: 'Sabine' },
    { name: 'Sander', gender: 'm' },
    { name: 'Sandrine', gender: 'f' },
    { name: 'Sergio', gender: 'm' },
    { name: 'Stanley', gender: 'm' },
    { name: 'Tedrick', gender: 'm' },
    { name: 'Theda', gender: 'f' },
    { name: 'Toka' },
    { name: 'Wanda', gender: 'f' },
    { name: 'Wilandra', gender: 'f' },
  ],
  last: [
    'Abirwik',
    'Achterberg',
    'Andal',
    'Blyth',
    'Botello',
    'Brea',
    'Canton',
    'Corlett',
    'Cota',
    'Dekker',
    'Elken',
    'Fragoso',
    'Frostenden',
    'Geoghagan',
    'Giano',
    'Goris',
    'Groothalle',
    'Hanflik',
    'Holloway',
    'Holt',
    'Igwe',
    'Kilobo',
    'Largala',
    'Lokrig',
    'Luria',
    'Mentink',
    'Mink',
    'Miramond',
    'Nova',
    'Orlow',
    'Pino',
    'Reza',
    'Rocha',
    'Ryllyngton',
    'Sharow',
    'Staynhouse',
    'Tenorio',
    'Thwenge',
    'Toka',
    'Tuswell',
    'Wainwright',
    'Wegstapel',
  ],
};
