export default {
  first: [
    'Afonso',
    'Alberte',
    'Aldara',
    'Aleixo',
    'Amaro',
    'Antía',
    'Antón',
    'Anxo',
    'Artur',
    'Barend',
    'Bart',
    'Bartel',
    'Bartholomeus',
    'Bas',
    'Bastiaan',
    'Beatrix',
    'Beau',
    'Ben',
    'Benedictus',
    'Benjamin',
    'Bente',
    'Benthe',
    'Berend',
    'Berendina',
    'Bernard',
    'Bernhard',
    'Bert',
    'Betje',
    'Bob',
    'Boele',
    'Bonifaas',
    'Boudewijn',
    'Braam',
    'Bram',
    'Brecht',
    'Brechtje',
    'Brigitta',
    'Broos',
  ],
  last: [
    'García',
    'González',
    'Rodríguez',
    'Fernández',
    'López',
    'Martínez',
    'Sánchez',
    'Pérez',
    'Gómez',
    'Ruíz',
    'Díaz',
    'Álvarez',
    'Romero',
    'Alonso',
    'Gutiérrez',
    'Torres',
    'Domínguez',
    'Vázquez',
    'Ramos',
    'Gil',
    'Ramírez',
    'Blanco',
    'Suárez',
    'Ortega',
    'Delgado',
    'Castro',
    'Iglesias',
    'Núñez',
    'Garrido',
    'Castillo',
    'Cortés',
    'Guerrero',
    'Prieto',
    'Méndez',
    'Calvo',
    'Vidal',
    'Gallego',
    'Cruz',
    'Herrera',
    'Peña',
    'Baas',
    'Beekhof',
    'de Boer',
    'Braam',
    'Bruin',
    'Buskirk',
    'Citroen',
    'Dekker',
    'Elzinga',
    'de Graaf',
    'de Haan',
    'de Haas',
    'van der Heide',
    'van den Heuval',
    'van de Hoek',
    'van het Hoff',
    'van der Kleij',
    'Kuiper',
    'de Lange',
    'van der Linden',
    'van der Meer',
    'Mesman',
    'Meulenbelt',
    'der Molen',
    'Ruysch',
    'Stoepker',
    'Teuling',
    'Tuinstra',
    'Vinke',
    'Visser',
    'van Vliet',
    'Vos',
    'de Wees',
    'van Westhuizen',
    'de Windt',
  ],
};
