name: Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Install Python Dependencies
        run: |
          sudo apt-get install -y python3-setuptools
          sudo pip3 install -r requirements.txt

      - name: Prettier
        run: npx prettier --check src/


        run: black --check .

      - name: Black
        run: black --check .

      - name: Test
        run: nosetests test
