name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Prettier
        run: npx prettier --check \"**/*.{js,jsx,ts,tsx,json,md,mdx}\"

      - name: Lint
        run: yarn lint

      - name: Unit Tests
        run: yarn test

      - name: Build
        run: yarn gatsby build
