name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i

      - name: Prettier
        run: npx prettier --check **/*.{js,ts,tsx,json,md,mdx}

      # - name: Lint
        # run: yarn lint

      #- name: Unit Tests
        #run: yarn test
